spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone : http://localhost:2000/eureka/
server:
  port: 80
logging:
  level:
    root: info
    com.example.springcloudzuul: debug
zuul:
  ribbon-isolation-strategy: thread
  host:
    max-total-connections: 1000
    max-per-route-connections: 200
  routes:
    jwt-service:
      path: /jwt/**
      sensitiveHeaders: Cookie,Set-Cookie