spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/你自己的github名称/spring-cloud-project.git
          search-paths:
              - config-repos/config-client-config
          username: 用户名
          password: 密码
  application:
    name: config-server
server:
  port: 1000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka