spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/你自己的github名称/config-repos.git
          search-paths:
            - config-client-config
          username: ******
          password: ******
  application:
    name: config-server
server:
  port: 1000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka